web-app/config/routes.rb
Rails.application.routes.draw do
  resources :profile, :trackers, :points

  # get 'history_show/:id' => 'history_show#shows', as: 'history_show'

  ActiveAdmin.routes(self)
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact',   to: 'static_pages#contact'

  get 'api_for_trackers/validate_tracker'
  get 'api_for_trackers/aaaa'
  get 'api_for_trackers/accept_message'

  post 'api_for_parser/:imei/save_message', to: 'api_for_parser#save_message'

end

web-app/app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

web-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web-app/app/models/point.rb
class Point < ApplicationRecord
  belongs_to :tracker
  validates :longtitude, presence: true,
                         inclusion: { in: -180...180 }, numericality: true
  validates :latitude, presence: true,
                       inclusion: { in: -90...90 }, numericality: true
end

web-app/app/models/protocol.rb
class Protocol < ApplicationRecord
  has_many :trackers
end

web-app/app/models/tracker.rb
class Tracker < ApplicationRecord
  validates :imei_code, presence: true, imei: true, uniqueness: true

  validates :phone, presence: true

  belongs_to :user

  has_many :points

  belongs_to :protocol
end

web-app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :phone_number, presence: true

  has_many :trackers
end

web-app/app/controllers/api_for_parser_controller.rb
class ApiForParserController < ApplicationController



  skip_before_action :verify_authenticity_token, only: [:save_message]

  def save_message
    imei = params[:imei]

    tracker = Tracker.find_by(:imei_code => imei)

    @point = Point.new
    @point.tracker = tracker
    @point['longtitude'] = params[:longtitute]
    @point['latitude'] = params[:latitude]
    @point['point_time'] = params[:time]
    @point['message'] = params[:type]

    if @point.save

    else
      p @point.errors.messages
    end


      # p message
     # render json: params
  end

  private
  def message_params
    params.permit(:time, :type)
  end
end

web-app/app/controllers/api_for_trackers_controller.rb
class ApiForTrackersController < ApplicationController
  before_action :set_tracker

  def validate_tracker
    respond_to do |format|
      if @tracker.nil?
        render status: :not_found  
      else
        format.json { render action: 'accept_message', status: 200 }
      end
    end
  end

  def aaaa
    render json: { message: 'Hello there' }, status: :ok
  end

  def accept_message
    render json: { message: "#{@tracker.protocol.id}" }, status: :ok
  end

  private

  def set_tracker
    @tracker = nil
    begin
       @tracker = Tracker.find_by(imei_code: params.require(:imei))
    rescue => exception
      puts exception
    end
  end
end

web-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :active_user, if: :devise_controller?

  private

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in'
      redirect_to login_url
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :phone_number])
    # devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :phone_number) }
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      new_user_session_path
    else
      redirect_to :back
    end 
  end
  
  def active_user
    if current_user && current_user.active == false
       sign_out_and_redirect(current_user)
       flash[:danger] = 'Ваш аккаунт не активирован пожалуйста обратитесь в тех.поддержку'
    end
  end

  def gmap 
    @users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end
end

web-app/app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authenticate_user!
  before_action :find_params_id, only: [:show, :update]

  def index
  	@users = current_user.trackers.all
  end

  def update
    if @tracker.active == true
    @tracker.update_attribute(:active, false)
      redirect_to profile_index_path
    else
      @tracker.update_attribute(:active, true)
      redirect_to profile_index_path
    end
  end

  private

  def find_params_id
    @tracker = Tracker.find(params[:id])
  end
end

web-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

web-app/app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def index

  end

  def show
  	@tracker = Tracker.find(params[:id])
  	@points = @tracker.points

  	# @hash = Gmaps4rails.build_markers(@points) do |tracker, marker|
  	#   marker.lat tracker.latitude
  	#   marker.lng tracker.longtitude
   #    marker.infowindow tracker.message
  	# end
   #  p @hash
  end

  private

  def tracker_params
    params.require(:tracker).permit(:longtitude, :latitude, :tracker_id)
  end
end

web-app/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

web-app/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

web-app/app/helpers/api_for_parser_helper.rb
module ApiForParserHelper
end

web-app/app/helpers/api_for_trackers_helper.rb
module ApiForTrackersHelper
end

web-app/app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "GPS Track-Car"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

web-app/app/helpers/profile_helper.rb
module ProfileHelper
end

web-app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

web-app/app/helpers/trackers_helper.rb
module TrackersHelper
end

web-app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">ESDP Project</a>
    by <a href="#">group #4</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "О нас",   about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
    </ul>
  </nav>
</footer>

web-app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Track-Car", root_path, id: "logo" %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Дом",    root_path %></li>
        <li><%= link_to "Помощь",    help_path %></li>
        <li><a type="button" data-toggle="modal" data-target="#myModal">
        Контакты
        </a></li>
     <% if user_signed_in? %>
        <!-- Devise Если залогинился-->
        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Привет, <%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Редактирование', edit_user_registration_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></li>
            <li><%= link_to 'Админ Панель', admin_root_path %></li>
          </ul>
        </li>
          <li><%= link_to 'Профиль', profile_index_path %></li>
     <% else %>
        <!-- Devise Если не залогинился-->
        <li><%= link_to "Войти", new_user_session_path %></li>
     <% end %>
    </ul>
    </nav>
  </div>
</header>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contacts</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

web-app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

web-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>