web-app/config/routes.rb
Rails.application.routes.draw do
  resources :profile, :trackers, :points

  # get 'history_show/:id' => 'history_show#shows', as: 'history_show'

  ActiveAdmin.routes(self)
  devise_for :users
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact',   to: 'static_pages#contact'

  get 'api_for_trackers/validate_tracker'
  get 'api_for_trackers/aaaa'
  get 'api_for_trackers/accept_message'

  post 'api_for_parser/:imei/save_message', to: 'api_for_parser#save_message'

end

web-app/app/models/tracker.rb
class Tracker < ApplicationRecord
  validates :imei_code, presence: true, imei: true, uniqueness: true

  validates :phone, presence: true

  belongs_to :user

  has_many :points

  belongs_to :protocol
end

web-app/app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def index

  end

  def show
  	@tracker = Tracker.find(params[:id])
  	@points = @tracker.points

  	# @hash = Gmaps4rails.build_markers(@points) do |tracker, marker|
  	#   marker.lat tracker.latitude
  	#   marker.lng tracker.longtitude
   #    marker.infowindow tracker.message
  	# end
   #  p @hash
  end

  private

  def tracker_params
    params.require(:tracker).permit(:longtitude, :latitude, :tracker_id)
  end
end

web-app/app/helpers/trackers_helper.rb
module TrackersHelper
end

web-app/app/views/trackers/index.html.erb
<h1>Trackers#index</h1>
<p>Find me in app/views/trackers/index.html.erb</p>

web-app/app/views/trackers/show.html.erb
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css"
          integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ=="
          crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"
        integrity="sha512-A7vV8IFfih/D732iSSKi20u/ooOfj/AGehOKq0f4vLT1Zr2Y+RX7C+w8A1gaSasGtRUZpF/NZgzSAu4/Gc41Lg=="
        crossorigin=""></script>
 
<div class="container">
<div class="col-lg-12 col-sm-8">
  <div class="card hovercard">
    <div class="card-background">
      <img class="card-bkimg" alt="" src="/image/avatar.jpg">
      <!-- http://lorempixel.com/850/280/people/9/ -->
    </div>
    <div class="useravatar">
      <img alt="" src="/image/ava.png">
    </div>
    <div class="card-info"> <span class="card-title"><%= link_to current_user.email, profile_index_path %></span>
    </div>
  </div>
  <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <div class="hidden-xs">Online</div>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
        <div class="hidden-xs">Messages</div>
      </button>
    </div>
  </div>

 <div class="well">
    <div class="tab-content">
      <div class="tab-pane fade in active" id="tab1">
        <!-- <center> -->
          <div style='width: 800px;'>
            <div id="map" style='width: 1070px; height: 400px;'></div>
          </div>
        <!-- </center> -->
      </div>
          <% else %>
      <div class="tab-pane fade in" id="tab3">
        <table class="table">
          <tr>
          <td><h3>Отправлено</td>
          <td><h3>Сообщение</td> 
          </tr>
        <% @tracker.points.each do |point| %>
          <tr>
          <td><%= point.updated_at.strftime("%B %e, %Y at %I:%M %p") %></td> 
          <td><%= point.message %></td>
        </tr>
        <% end %>
        </table> 
      </div>
    </div>
  </div>
</div>
</div>

<div id="map" style="width: 600px; height: 400px"></div>

  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>

</script>
    <script type="text/javascript">
    var points = [];
  <% @points.each do |p| %>
    points.push([<%= p.latitude %>, <%= p.longtitude %>]);
  <% end %>
  var mapContainer = 'map';
  var startViewPoint = [42.8746, 74.5698];

  var mymap = L.map(mapContainer).setView(startViewPoint, 13);

  L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    id: 'mapbox.streets'
  }).addTo(mymap);

  var polyline = L.polyline(points, {color: 'red'}).addTo(mymap);
  mymap.fitBounds(polyline.getBounds());

  points.forEach(function(point) {
    L.circleMarker(point, {
      fill:true,
      fillOpacity: 1,
      radius: 3
    }).addTo(mymap);
  });
    </script>